version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6370:6379"

  lab-service:
    build: ../src/laboratory_service
    container_name: laboratory-service
    volumes:
      - ../src/laboratory_service/bio_lab.db:/app/bio_lab.db
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=8

  patient-service:
    build: ../src/patient_service
    container_name: patient-service
    volumes:
      - ../src/patient_service/bio.db:/app/bio.db
    ports:
      - "8002:8002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=8
